INSERT INTO CURRENCY (CODE_ISO,DESCRIPTION_CURRENCY,COUNTRY) VALUES ('PEN', 'SOLES','PERÚ');
INSERT INTO CURRENCY (CODE_ISO,DESCRIPTION_CURRENCY,COUNTRY) VALUES ('USD', 'DOLARES','ESTADOS UNIDOS');
INSERT INTO CURRENCY (CODE_ISO,DESCRIPTION_CURRENCY,COUNTRY) VALUES ('EUR', 'EUROS','ITALIA');
INSERT INTO CURRENCY (CODE_ISO,DESCRIPTION_CURRENCY,COUNTRY) VALUES ('GBP', 'LIBRAS ESTERLINAS','REINO UNIDO');
INSERT INTO CURRENCY (CODE_ISO,DESCRIPTION_CURRENCY,COUNTRY) VALUES ('CAD', 'DÓLAR CANADIENSE','CANADA');
INSERT INTO CURRENCY (CODE_ISO,DESCRIPTION_CURRENCY,COUNTRY) VALUES ('CLP', 'PESO CHILENO','CHILE');
INSERT INTO CURRENCY (CODE_ISO,DESCRIPTION_CURRENCY,COUNTRY) VALUES ('CRC', 'COLÓN COSTARRICENSE','COSTA RICA');
INSERT INTO CURRENCY (CODE_ISO,DESCRIPTION_CURRENCY,COUNTRY) VALUES ('VEF', 'BOLÍVAR FUERTE','VENEZUELA');
